name: CI Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  app-tests:
    name: Next.js App (Build + Tests)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: 'npm'
        cache-dependency-path: './app/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Build check
      run: npm run build
      env:
        NASA_API_KEY: DEMO_KEY
